### ISSUE TITLE
Combining validations of a single item

### ISSUE THREAD

**Issue by miloszm** [DanielaSfregola/data-validation#8]
#Hi Daniela - I followed solutions from your Scala Exchange talk and this project, and it worked out for me pretty well. That was a really nice approach and a good use of Cats IMO. My question relates to the case in which I have two or more validations per case class member, and I need to combine these validations. It turns out there is no easy way to combine 2 or more ValidatedNel (or similar) objects into one. The provided "combine" method is not ideal, as it combines not only errors (which is desired), but unfortunately also values. I ended up tweaking my value type, having its "combine" method overridden (by forming a semigroup with trivial one-sided combination). Please have a look at examples in project [https://github.com/miloszm/scala-validation](https://github.com/miloszm/scala-validation), there is a little Word document there in the docs folder with pointers to relevant examples. Classes `CombineValidator` and `CombineValidatorImproved` and their tests illustrate the gist of the problem.

**Comment by DanielaSfregola** [comment]
Hi @miloszm,
what I would personally do is creating a function that validates everything regarding a case class member.

For example,
you can each function to represent all the validations for a case class member.

For example, you could rewrite [this code](https://github.com/miloszm/scala-validation/blob/master/src/main/scala/com/ce/CombineValidatorImproved.scala#L13) as following:

```scala
def validateEmail(e: String): ValidatedNel[Err, String] = 
  (validateEmailByRegex(e) |@| validateEmailByKeyword(e, "good") |@| validEmailFormat(e)) map { case _ => e }

def validatePhone(p: String): ValidatedNel[Err, String] = 
  (validatePhoneByPrefix(p, "+44") |@| validatePhoneByRegex(p) |@| validPhoneFormat(p)) map { case _ => p }

def validateData(d: Data): ValidatedNel[Err, Str] = 
  (validateEmail(d.email) |@| validatePhone(d.phone)).map(Data)
```

Note the little trick in `validateEmail` and `validatePhone` that if the case class member is valid, then I just return it as Valid(_)in ValidatedNel.

Also, you do not really need functions here, you can just do the same with vals:
```scala
def validateData(d: Data): ValidatedNel[Err, Str] =  {
  val emailValidation = (validateEmailByRegex(d.email) |@| validateEmailByKeyword(d.email, "good") |@| validEmailFormat(d.email)) map { case _ => d.email }
  val phoneValidation = (validatePhoneByPrefix(d.phone, "+44") |@| validatePhoneByRegex(d.phone) |@| validPhoneFormat(d.phone)) map { case _ => d.phone }
  (emailValidation |@| phoneValidation).map(Data)
}
```

I personally prefer the first version, as it makes easier to reuse the code -- but I believe they are both fine.

Does this help with your issue?

Cheers,
Daniela

**Comment by DanielaSfregola** [comment]
If you want to see some actual code in action, in commit https://github.com/DanielaSfregola/data-validation/commit/cb142c2bd6fe48869022815049bac4c9f0a6c4a7 I have added an explicit example of doing this.

Cheers,
Daniela

**Comment by miloszm** [comment]
It works - this solves the problem in an elegant and simple way, thanks.
Cheers,
Milosz
